### ISSUE TITLE
JsonConvert.GetUtcOffset throws System.TimeZoneNotFoundException

### ISSUE THREAD

**Issue by jamesantrobus** [chrisntr/Newtonsoft.Json#5]
Getting this when running a device only - works ok in the simulator.

SO question relating to this here: http://stackoverflow.com/questions/4270099/timezone-always-returns-timezonenotfoundexception 

Updating JsonConvert.GetUtcOffSet seems to fix the issue https://gist.github.com/826443 - not sure of the implications of this as the unit tests aren't running

**Comment by jamesantrobus** [comment]
Console output pulled from Xcode organizer https://gist.github.com/824403

**Comment by aproteau** [comment]
I have the same issue.  Any workaround ?
